# Site settings
title: "@euronion's website"
description: "A website for stuff ..."
baseurl: ""
url: "https://euronion.github.io"

# User settings
username: euronion
user_title: user_title
email: set-a-email-contact@future-maybe
twitter_username: euronion
github_username:  euronion
profile_picture: https://http.cat/418

# Build settings
markdown: kramdown # Markdown style to use
highlighter: rouge # Syntax highlighter used for code
permalink: /:categories/:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/euronion
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/euronion
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: This website
    url: https://euronion.github.io

# exclude node related stuff
exclude: ['package.json', 'src', 'node_modules']
